# Generated by Django 3.0.6 on 2020-06-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
